/** Central copy for info tooltips across the app */
export const TOOLTIPS = {
  contact: {
    name: "Enter your full name using letters and spaces only (minimum 2 characters).",
    phone:
      "Include country code if needed. Example: +91 6363620044. We use this to call you back.",
    email: "We will send a reply to this email address about your enquiry.",
    enquiryType:
      "Choose the option that best matches your request so our team can respond faster.",
    message:
      "Share your destination, travel dates, group size, or any special requirements (at least 10 characters).",
  },
  booking: {
    email:
      "Booking confirmation and tour details will be sent to this email address.",
    phone:
      "Active mobile number with at least 10 digits. Our team may call to confirm your trip.",
    travelDate:
      "Select the date you plan to start travelling. Must be today or a future date.",
    confirm:
      "Submitting sends your request to Ramesh Tours & Travels. We will contact you to confirm availability and payment.",
  },
  packages: {
    bookNow:
      "Opens a quick booking form. Enter your contact details and preferred travel date — no payment on this step.",
    perPerson: "Price shown is per traveller unless stated otherwise in the package.",
    badge: "Featured or limited-availability tour package.",
  },
  assistant: {
    fab: "Ask our AI travel assistant about packages, destinations, and trip ideas across India.",
    input:
      "Powered by Google Gemini. Ask about tours, itineraries, or travel tips for your next trip.",
    poweredBy:
      "Responses are generated by Google Gemini and tailored for Ramesh Tours & Travels.",
  },
  insights: {
    listedTours: "Total number of tour packages currently listed on the site.",
    regions: "Number of distinct regions or states covered by our packages.",
    startingFrom: "Lowest per-person price among all listed packages.",
    average: "Average per-person price across all listed packages.",
    travelStyle: "How packages are grouped by type of experience (e.g. spiritual, adventure).",
    regionChart: "Share of packages across different regions of India.",
    priceTier: "Number of packages in each price range per person.",
  },
  general: {
    scrollTop: "Scroll back to the top of the page",
    workingHours: "We are available during these hours for calls and enquiries.",
  },
} as const;
